[package]
name = "kodade-cli"
version = "0.2.1"
edition.workspace = true
license.workspace = true

[[bin]]
name = "kodade-cli"
path = "src/main.rs"

[dependencies]
base64.workspace = true
clap.workspace = true
clap_complete.workspace = true
serde_json.workspace = true
dirs.workspace = true
flate2.workspace = true
getrandom.workspace = true
anyhow.workspace = true
crossterm.workspace = true
kodade-cli-daemon = { path = "../kodade-cli-daemon" }
kodade-cli-proto = { path = "../kodade-cli-proto" }
libc.workspace = true
ratatui.workspace = true
regex.workspace = true
serde.workspace = true
semver.workspace = true
sha2.workspace = true
zip.workspace = true
tar.workspace = true
tokio.workspace = true
toml.workspace = true
toml_edit.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
