[package]
name = "kodade-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "kodade-cli"
path = "src/main.rs"

[dependencies]
dirs.workspace = true
anyhow.workspace = true
crossterm.workspace = true
kodade-cli-daemon = { path = "../kodade-cli-daemon" }
kodade-cli-proto = { path = "../kodade-cli-proto" }
libc.workspace = true
ratatui.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
