[package]
name = "kodade-cli-daemon"
version = "0.3.1"
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
anyhow.workspace = true
dirs.workspace = true
flate2.workspace = true
libc.workspace = true
kodade-cli-proto = { path = "../kodade-cli-proto" }
portable-pty.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
vt100.workspace = true
vte.workspace = true
unicode-width.workspace = true
png.workspace = true
getrandom.workspace = true
