#!/bin/sh
# Render the Homebrew formula for one release from its SHA256SUMS file.
# Usage: scripts/homebrew-formula.sh VERSION SHA256SUMS > Formula/kodade-cli.rb
# The release workflow runs this after publishing and pushes the result to
# the Kodade/homebrew-tap repository.
set -eu

VERSION="$1"
SUMS="$2"
BASE="https://github.com/Kodade/kodade-cli/releases/download/v${VERSION}"

# sum TARGET — the checksum recorded for one target's tarball.
sum() {
  awk -v name="kodade-cli-${VERSION}-$1.tar.gz" '$2 == name { print $1 }' "$SUMS"
}

for target in aarch64-apple-darwin x86_64-apple-darwin aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu; do
  if [ -z "$(sum "$target")" ]; then
    echo "missing checksum for $target in $SUMS" >&2
    exit 1
  fi
done

cat <<EOF
# Generated by scripts/homebrew-formula.sh in Kodade/kodade-cli; do not edit by hand.
class KodadeCli < Formula
  desc "Terminal workspace for agent CLIs: workspaces, tabs, panes, agent-state awareness"
  homepage "https://github.com/Kodade/kodade-cli"
  version "${VERSION}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "${BASE}/kodade-cli-${VERSION}-aarch64-apple-darwin.tar.gz"
      sha256 "$(sum aarch64-apple-darwin)"
    end
    on_intel do
      url "${BASE}/kodade-cli-${VERSION}-x86_64-apple-darwin.tar.gz"
      sha256 "$(sum x86_64-apple-darwin)"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/kodade-cli-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$(sum aarch64-unknown-linux-gnu)"
    end
    on_intel do
      url "${BASE}/kodade-cli-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$(sum x86_64-unknown-linux-gnu)"
    end
  end

  def install
    bin.install "kodade-cli"
    generate_completions_from_executable(bin/"kodade-cli", "completion")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kodade-cli --version")
  end
end
EOF
